"""add statuses for order and courier

Revision ID: 733253274957
Revises: d8bc2f02e92b
Create Date: 2024-05-24 16:47:09.651922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '733253274957'
down_revision: Union[str, None] = 'd8bc2f02e92b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    courier_statuses = postgresql.ENUM('idle', 'busy', name='courierstatuses')
    courier_statuses.create(op.get_bind())

    order_statuses = postgresql.ENUM('created', 'finished', name='orderstatuses')
    order_statuses.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courier', sa.Column('status', courier_statuses, nullable=False))
    op.add_column('order', sa.Column('status', order_statuses, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'status')
    op.drop_column('courier', 'status')
    # ### end Alembic commands ###
    bind = op.get_bind()
    sa.Enum(name='courierstatuses').drop(bind, checkfirst=False)
    sa.Enum(name='orderstatuses').drop(bind, checkfirst=False)
